# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Merge Branch

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend 

      - name: Build the project
        run: npm run build
        working-directory: ./frontend 
  merge:
    runs-on: ubuntu-latest
    needs: build
    uses: actions/checkout@v2

      - name: merge-into-main
          run: |
            git checkout main
            git pull origin main
            git merge feature/pr-from-action
            git push origin main
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
