# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Merge Branch

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend 

      - name: Build the project
        run: npm run build
        working-directory: ./frontend 

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Create Pull Request
        run: |
          git config --global user.name "deakay13"
          git config --global user.email "nguyenleduykhang13@gmail.com"
          git checkout -b feature/pr-from-action
          git add .
          git commit -m "Automated PR: Build successful"
          gh pr create --base main --head feature/pr-from-action --title "Automated PR" --body "This PR was created automatically after a successful build."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch origin

      - name: Merge feature branch into main
        run: |
          git checkout main
          git pull origin main
          git merge feature/pr-from-action
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

